//! Content heuristics for the code index and repo map (FR-FILTER-06).
//!
//! These decide what is worth *parsing and summarising*, not what exists:
//! `grep` still searches a generated file if asked to.

use std::io::Read;
use std::path::Path;

/// How much of a file the heuristics look at.
const SNIFF_BYTES: usize = 64 * 1024;

/// A NUL byte in the first 8 KiB, as ripgrep decides it.
pub fn looks_binary(head: &[u8]) -> bool {
    head.iter().take(8 * 1024).any(|b| *b == 0)
}

/// One enormous line, or lines that are long on the whole: bundler output.
pub fn looks_minified(text: &str) -> bool {
    let mut lengths: Vec<usize> = text.lines().map(str::len).collect();
    if lengths.iter().any(|l| *l > 5_000) {
        return true;
    }
    if lengths.len() < 3 {
        return false;
    }
    lengths.sort_unstable();
    lengths[lengths.len() / 2] > 300
}

/// Conventional "generated, do not edit" markers in the first lines.
pub fn looks_generated(text: &str) -> bool {
    text.lines().take(5).any(|l| {
        l.contains("@generated")
            || l.contains("DO NOT EDIT")
            || l.contains("autogenerated")
            || l.contains("auto-generated")
    })
}

pub fn is_lockfile(name: &str) -> bool {
    name.ends_with(".lock")
        || matches!(
            name,
            "package-lock.json" | "pnpm-lock.yaml" | "yarn.lock" | "go.sum" | "npm-shrinkwrap.json"
        )
}

/// Worth parsing into the code index and naming in the repo map.
pub fn worth_indexing(path: &Path) -> bool {
    if path
        .file_name()
        .and_then(|n| n.to_str())
        .is_some_and(is_lockfile)
    {
        return false;
    }
    let Ok(file) = std::fs::File::open(path) else {
        return false;
    };
    let mut head = Vec::with_capacity(SNIFF_BYTES);
    if file
        .take(SNIFF_BYTES as u64)
        .read_to_end(&mut head)
        .is_err()
    {
        return false;
    }
    if looks_binary(&head) {
        return false;
    }
    let text = String::from_utf8_lossy(&head);
    !looks_minified(&text) && !looks_generated(&text)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_binary_minified_generated_and_lockfiles() {
        assert!(looks_binary(b"abc\0def"));
        assert!(!looks_binary(b"plain text"));
        assert!(looks_minified(&"x".repeat(6_000)));
        assert!(looks_minified(&format!("{}\n", "y".repeat(400)).repeat(5)));
        assert!(!looks_minified("fn main() {\n    println!(\"hi\");\n}\n"));
        assert!(looks_generated(
            "// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x"
        ));
        assert!(looks_generated("# @generated by tool\n"));
        assert!(!looks_generated("// ordinary\n"));
        assert!(is_lockfile("Cargo.lock"));
        assert!(is_lockfile("package-lock.json"));
        assert!(!is_lockfile("lock.rs"));
    }
}
