use std::path::Path;
use std::sync::Arc;
use std::time::Duration;

use domain::{CodeIndexPort, IndexState, SearchPort, SymbolKind};
use infra_search::{FilterConfig, RipgrepSearch};

use crate::{spawn, store, CodeIndex, IndexOptions};

fn write(root: &Path, rel: &str, text: &str) {
    let p = root.join(rel);
    std::fs::create_dir_all(p.parent().expect("parent")).expect("mkdir");
    std::fs::write(p, text).expect("write");
}

/// Bump a file's mtime so a same-size rewrite is still noticed.
fn touch_later(root: &Path, rel: &str) {
    let p = root.join(rel);
    let f = std::fs::File::options()
        .append(true)
        .open(&p)
        .expect("open");
    let later = std::time::SystemTime::now() + Duration::from_secs(5);
    f.set_modified(later).expect("set mtime");
}

fn project() -> tempfile::TempDir {
    let dir = tempfile::tempdir().expect("tempdir");
    let r = dir.path();
    write(r, "go.mod", "module example.com/svc\n");
    write(
        r,
        "src/lib.rs",
        "pub mod engine;\nuse crate::engine::Engine;\n\npub fn start() -> Engine { Engine::new() }\n",
    );
    write(
        r,
        "src/engine.rs",
        "/// Runs.\npub struct Engine;\n\nimpl Engine {\n    pub fn new() -> Self { Engine }\n    pub fn execute(&self) {}\n}\n",
    );
    write(
        r,
        "api/server.go",
        "package api\n\ntype Server struct{}\n\nfunc (s *Server) Run() {}\n",
    );
    write(
        r,
        "cmd/main.go",
        "package main\n\nimport \"example.com/svc/api\"\n\nfunc main() { _ = api.Server{} }\n",
    );
    write(
        r,
        "web/app.ts",
        "import { helper } from './util';\nexport function app() { return helper(); }\n",
    );
    write(r, "web/util.ts", "export function helper() { return 1; }\n");
    write(
        r,
        "py/models.py",
        "class User:\n    def save(self):\n        pass\n",
    );
    write(
        r,
        "node_modules/dep/index.ts",
        "export function hidden() {}\n",
    );
    write(
        r,
        "gen/types.go",
        "// Code generated by protoc. DO NOT EDIT.\npackage gen\n\nfunc Gen() {}\n",
    );
    write(r, "README.md", "# not code\n");
    dir
}

fn search(root: &Path) -> Arc<dyn SearchPort> {
    Arc::new(RipgrepSearch::new(root, &FilterConfig::default()).expect("search"))
}

fn index(root: &Path) -> Arc<CodeIndex> {
    let idx = CodeIndex::open(IndexOptions::new(root), search(root));
    idx.build();
    idx
}

#[test]
fn a_build_indexes_supported_files_and_skips_excluded_and_generated_ones() {
    let dir = project();
    let idx = index(dir.path());
    assert_eq!(idx.state(), IndexState::Ready);
    let stats = idx.stats();
    assert_eq!(stats.files, 8, "{stats:?}"); // node_modules excluded, README has no grammar, gen/ kept as skipped
    assert_eq!(stats.skipped.get("generated"), Some(&1));
    assert!(idx
        .symbols("hidden", None, None, 10)
        .expect("symbols")
        .is_empty());
    assert!(idx
        .symbols("Gen", None, None, 10)
        .expect("symbols")
        .is_empty());
}

#[test]
fn symbols_rank_exact_then_prefix_then_fuzzy_and_filter_by_kind_and_path() {
    let dir = project();
    let idx = index(dir.path());
    let names = |q: &str, k: Option<SymbolKind>, p: Option<&str>| -> Vec<String> {
        idx.symbols(q, k, p, 20)
            .expect("symbols")
            .into_iter()
            .map(|d| d.qualified)
            .collect()
    };
    assert_eq!(names("Engine", Some(SymbolKind::Struct), None), ["Engine"]);
    assert_eq!(names("exe", None, None), ["Engine::execute"]);
    assert_eq!(names("Engine::new", None, None), ["Engine::new"]);
    assert_eq!(names("Server.Run", None, None), ["Server.Run"]);
    assert_eq!(names("hlpr", None, None), ["helper"]);
    // `Function` includes methods; a path prefix narrows.
    assert_eq!(
        names("save", Some(SymbolKind::Function), Some("py")),
        ["User.save"]
    );
    assert!(names("save", None, Some("web")).is_empty());
    let first = names("start", None, None);
    assert_eq!(first.first().map(String::as_str), Some("start"));
}

#[test]
fn outline_covers_files_directories_and_unsupported_languages() {
    let dir = project();
    let idx = index(dir.path());
    let file = idx
        .outline("src/engine.rs")
        .expect("ok")
        .expect("supported");
    let quals: Vec<&str> = file.iter().map(|d| d.qualified.as_str()).collect();
    assert_eq!(
        quals,
        ["Engine", "Engine", "Engine::new", "Engine::execute"]
    );
    assert_eq!(file[0].span.start_line, 1, "doc comment included");
    assert_eq!(file[2].signature, "pub fn new() -> Self { Engine }");
    let top = idx.outline("web").expect("ok").expect("dir");
    let names: Vec<&str> = top.iter().map(|d| d.name.as_str()).collect();
    assert_eq!(names, ["app", "helper"]);
    assert_eq!(idx.outline("README.md").expect("ok"), None);
    assert!(idx.outline("nope.rs").is_err());
    // An absolute path inside the root is the same file.
    let abs = dir.path().join("src/engine.rs");
    assert_eq!(
        idx.outline(abs.to_str().expect("utf8"))
            .expect("ok")
            .map(|d| d.len()),
        Some(4)
    );
}

#[test]
fn locate_prefers_exact_qualified_names_and_honours_the_path() {
    let dir = project();
    let idx = index(dir.path());
    let hits = idx.locate(None, "Engine::execute").expect("locate");
    assert_eq!(hits.len(), 1);
    assert_eq!(
        (hits[0].path.as_str(), hits[0].name_line),
        ("src/engine.rs", 6)
    );
    assert_eq!(idx.locate(None, "execute").expect("locate").len(), 1);
    assert!(idx
        .locate(Some("web"), "execute")
        .expect("locate")
        .is_empty());
    assert_eq!(
        idx.locate(None, "User.save").expect("locate")[0].kind,
        SymbolKind::Method
    );
}

#[test]
fn related_resolves_imports_both_ways_and_finds_references() {
    let dir = project();
    let idx = index(dir.path());
    let lib = idx.related("src/lib.rs").expect("related");
    assert_eq!(lib.imports, ["src/engine.rs"]);
    let engine = idx.related("src/engine.rs").expect("related");
    assert_eq!(engine.imported_by, ["src/lib.rs"]);
    let server = idx.related("api/server.go").expect("related");
    assert_eq!(server.imported_by, ["cmd/main.go"]);
    let util = idx.related("web/util.ts").expect("related");
    assert_eq!(util.imported_by, ["web/app.ts"]);
    let helper = idx.related("helper").expect("related");
    assert_eq!(helper.defined_in, ["web/util.ts:1"]);
    assert_eq!(helper.referenced_in, ["web/app.ts:1", "web/app.ts:2"]);
}

#[test]
fn notify_changed_updates_spans_at_once() {
    let dir = project();
    let idx = index(dir.path());
    write(
        dir.path(),
        "web/util.ts",
        "\n\nexport function helper() { return 1; }\nexport function added() {}\n",
    );
    idx.notify_changed("web/util.ts");
    let hits = idx.locate(Some("web/util.ts"), "helper").expect("locate");
    assert_eq!(hits[0].name_line, 3);
    assert_eq!(
        idx.symbols("added", None, None, 5).expect("symbols").len(),
        1
    );
}

#[test]
fn an_edit_made_outside_zcode_is_seen_on_the_next_query() {
    let dir = project();
    let idx = index(dir.path());
    write(
        dir.path(),
        "py/models.py",
        "class User:\n    def persist(self):\n        pass\n",
    );
    touch_later(dir.path(), "py/models.py");
    let hits = idx.symbols("persist", None, None, 5).expect("symbols");
    // A name the stale record lacks is found by the turn-start rescan…
    assert!(hits.is_empty() || hits[0].qualified == "User.persist");
    idx.rescan_changed();
    assert_eq!(
        idx.symbols("persist", None, None, 5)
            .expect("symbols")
            .len(),
        1
    );
    // …and a stale hit is refreshed by the query that returns it.
    write(
        dir.path(),
        "web/util.ts",
        "\nexport function helper() { return 2; }\n",
    );
    touch_later(dir.path(), "web/util.ts");
    let hits = idx.symbols("helper", None, None, 5).expect("symbols");
    assert_eq!(hits[0].name_line, 2);
}

#[test]
fn a_second_build_reuses_unchanged_files_and_reparses_only_the_touched_one() {
    let dir = project();
    let idx = index(dir.path());
    let first = idx.parses();
    assert!(first >= 6);
    touch_later(dir.path(), "src/lib.rs"); // same content: restamped, not parsed
    write(dir.path(), "web/util.ts", "export function helper2() {}\n");
    touch_later(dir.path(), "web/util.ts");
    let report = idx.build();
    assert_eq!(idx.parses() - first, 1);
    assert_eq!(report.parsed, 1);
}

#[test]
fn the_store_round_trips_and_a_warm_start_parses_nothing() {
    let dir = project();
    let idx = index(dir.path());
    let before = idx.stats();
    drop(idx);
    let opts = IndexOptions::new(dir.path());
    assert!(opts.store_path.exists());
    let warm = CodeIndex::open(opts, search(dir.path()));
    let report = warm.build();
    assert_eq!(warm.parses(), 0, "{report:?}");
    assert_eq!(warm.stats(), before);
    assert_eq!(
        warm.locate(None, "Engine::execute").expect("locate")[0].name_line,
        6
    );
}

#[test]
fn a_corrupt_or_foreign_store_is_discarded_and_rebuilt() {
    let dir = project();
    let idx = index(dir.path());
    let path = idx.options().store_path.clone();
    drop(idx);
    let bytes = std::fs::read(&path).expect("read");
    // Every truncation must be rejected, never panic.
    for cut in [0, 3, 10, bytes.len() / 2, bytes.len() - 1] {
        assert!(store::decode(&bytes[..cut]).is_err(), "cut at {cut}");
    }
    let mut other = bytes.clone();
    other[6] ^= 0xff; // extractor version
    assert!(store::decode(&other).is_err());
    std::fs::write(&path, b"garbage").expect("write");
    let fresh = index(dir.path());
    assert!(fresh.parses() >= 6);
    assert_eq!(fresh.stats().files, 8);
}

#[test]
fn deleted_files_leave_the_index() {
    let dir = project();
    let idx = index(dir.path());
    std::fs::remove_file(dir.path().join("web/util.ts")).expect("rm");
    idx.rescan_changed();
    assert!(idx
        .symbols("helper", None, None, 5)
        .expect("symbols")
        .is_empty());
    assert_eq!(idx.stats().files, 7);
}

#[test]
fn spawn_returns_before_the_build_and_reaches_ready() {
    let dir = project();
    let (tx, rx) = std::sync::mpsc::channel();
    let idx = spawn(
        IndexOptions::new(dir.path()),
        search(dir.path()),
        Some(Box::new(move |r: &crate::BuildReport| {
            let _ = tx.send(r.files);
        })),
    );
    // Queries work at any point of the build.
    let _ = idx.symbols("Engine", None, None, 5).expect("symbols");
    assert_eq!(rx.recv_timeout(Duration::from_secs(30)).expect("ready"), 8);
    assert_eq!(idx.state(), IndexState::Ready);
}

#[test]
fn oversized_files_are_recorded_as_skipped() {
    let dir = project();
    write(dir.path(), "src/big.rs", &"// pad\n".repeat(200));
    let mut opts = IndexOptions::new(dir.path());
    opts.max_file_bytes = 1_000;
    let idx = CodeIndex::open(opts, search(dir.path()));
    idx.build();
    assert_eq!(idx.stats().skipped.get("too large"), Some(&1));
    assert!(idx.outline("src/big.rs").is_err());
}

#[test]
fn parse_text_reports_syntax_errors_without_touching_the_index() {
    let dir = project();
    let idx = index(dir.path());
    let parsed = idx
        .parse_text("src/engine.rs", "fn a() {}\nfn b( {\n")
        .expect("ok")
        .expect("rust");
    assert!(parsed.error_nodes > 0);
    assert_eq!(parsed.defs[0].path, "src/engine.rs");
    assert_eq!(
        idx.locate(None, "Engine::execute").expect("locate").len(),
        1
    );
    assert_eq!(idx.parse_text("x.md", "# hi").expect("ok"), None);
}

#[test]
fn the_index_stays_small() {
    let dir = project();
    let idx = index(dir.path());
    assert!(idx.heap_bytes() < 64 * 1024, "{}", idx.heap_bytes());
}

/// NFR-CTX-MEM-02: ≤ 25 MB for 10k files. Slow; run explicitly.
#[test]
#[ignore]
fn index_heap_under_budget_for_10k_files() {
    let dir = tempfile::tempdir().expect("tempdir");
    for i in 0..10_000 {
        let body = (0..8)
            .map(|j| format!("pub fn f{i}_{j}(x: u32) -> u32 {{ let y{j} = x + {j}; y{j} }}\n"))
            .collect::<Vec<_>>()
            .concat();
        write(dir.path(), &format!("src/m{}/f{i}.rs", i % 100), &body);
    }
    let started = std::time::Instant::now();
    let idx = index(dir.path());
    let cold = started.elapsed();
    let heap = idx.heap_bytes();
    eprintln!("10k files: cold build {cold:?}, heap {} KiB", heap / 1024);
    assert_eq!(idx.stats().files, 10_000);
    assert!(heap <= 25 * 1024 * 1024);
    let t = std::time::Instant::now();
    for q in ["f5_3", "f99", "f1234_7", "zz"] {
        let _ = idx.symbols(q, None, None, 20).expect("symbols");
    }
    eprintln!("4 symbol queries: {:?}", t.elapsed());
    drop(idx);
    let t = std::time::Instant::now();
    let warm = index(dir.path());
    eprintln!("warm start: {:?}", t.elapsed());
    assert_eq!(warm.parses(), 0);
}
